import { env } from '@/env'

import '@/styles/globals.css'
import { Inter } from 'next/font/google'

import { type Metadata } from 'next'
import { type ReactNode } from 'react'

import { ContextProvider } from '@/lib/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: env.APP_NAME,
  description: 'Generated by create-wagmi',
}

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>{props.children}</ContextProvider>
      </body>
    </html>
  )
}
